---
title: "Climate change and temperature anomalies"
author: "Alice Chen(Group 14)"
date: "2022-09-11"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA's Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies we need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<p>Run the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>We have two objectives in this section:</p>
<ol style="list-style-type: decimal">
<li><p>Select the year and the twelve month variables from the <code>weather</code> dataset. We do not need the others (J-D, D-N, DJF, etc.) for this assignment.</p></li>
<li><p>Convert the dataframe from wide to 'long' format. Hint: use <code>gather()</code> or <code>pivot_longer()</code> function. Name the new dataframe as <code>tidyweather</code>, name the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p></li>
</ol>
<pre class="r"><code># drop unrelated columns
weather &lt;- select(weather,c(1:13)) 

# convert to tidy dataset for convinence
tidyweather &lt;- weather %&gt;%  
  pivot_longer(c(2:13), names_to = &quot;month&quot;, values_to = &quot;delta&quot;)</code></pre>
<p>Inspect our dataframe. It should have three variables now, one each for</p>
<ol style="list-style-type: decimal">
<li><p>year,</p></li>
<li><p>month, and</p></li>
<li><p>delta, or temperature deviation.</p></li>
</ol>
<div id="plotting-information" class="section level2">
<h2>1.2 Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trend line. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))


ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;,
    x= &quot;Year&quot;,
    y=&quot;Temperature Deviation&quot;
  )</code></pre>
<p><img src="/blogs/climate_change_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Q :
Is the effect of increasing temperature more pronounced in some months? Use <code>facet_wrap()</code> to produce a seperate scatter plot for each month, again with a smoothing line.</p>
<blockquote>
<p><strong>The graph shows that in relatively cold months (Oct, Nov, Dec, Jan, Feb, and Mar), the variation in temperature deviation is higher and the slopes of the trend lines are steeper than other months, which indicates that the effect of increasing temperature is more pronounced in those months when compared to summer months such as June, July, and August.</strong></p>
</blockquote>
<pre class="r"><code>tidyweather %&gt;% 
  group_by(month) %&gt;% 
  ggplot(aes(x=date, y = delta))+
  geom_point()+
  facet_wrap(~month)+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (title = &quot;Temperature Trends by Month&quot;,
        y=&quot;Temperature Deviation&quot;,
        x=&quot;Year&quot;)</code></pre>
<p><img src="/blogs/climate_change_files/figure-html/dist_of_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a temperature anomaly, as difference form the base period of 1951-1980. The code below creates a new data frame called comparison that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove data before 1800 and before using filter. Then, we use the mutate function to create a new variable interval which contains information on which period each observation belongs to. We can assign the different periods using case_when().</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Inspect the comparison dataframe by clicking on it in the Environment pane.</p>
<p>Now that we have the interval variable, we can create a density plot to study the distribution of monthly deviations (delta), grouped by the different time periods we are interested in. Set fill to interval to group and colour the data by different time periods.</p>
<pre class="r"><code># use fill=interval to group and colour the data by different time periods
ggplot(comparison, aes(x = delta, fill = interval, alpha = 1)) +
  guides(alpha = FALSE) +
  geom_density() +
      theme_bw() +
  labs (
    title = &quot;Temperature Deviations by Time Periods&quot;,
    x=&quot;Temperature Deviations&quot;,
    y=&quot;Delta&quot;
  )</code></pre>
<p><img src="/blogs/climate_change_files/figure-html/95_percent_CI-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using group_by() and summarise(), followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(mean_delta = mean(delta),na.rm=TRUE) 

#plotting the data:
average_annual_anomaly %&gt;% 
  ggplot(.,aes(x=Year,y=mean_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth(method = &quot;loess&quot;)+
  
  #change theme to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs(&quot;Average Annual Temperature Anomalies&quot;,
       x=&quot;Year&quot;,
       y=&quot;Mean Temperature Deviation&quot;)</code></pre>
<p><img src="/blogs/climate_change_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>1.3 Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Our task is to construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the infer package. Recall that the dataframe comparison has already grouped temperature anomalies according to time intervals; we are only interested in what is happening between 2011-present.</p>
<pre class="r"><code>library(infer)

formula_ci &lt;- comparison %&gt;% 

  # choose the interval 2011-present and calculate confidence interval stats
  filter(interval==&quot;2011-present&quot;) %&gt;% 
  group_by(interval) %&gt;% 
  summarise(mean_delta = mean(delta,na.rm=TRUE),
            SD_delta = sd(delta,na.rm=TRUE),
            count_delta=n(),
            se_delta = SD_delta/sqrt(count_delta),
            
            #We picked 95% confidence interval
            t_critical = qt(0.975,count_delta-1),
            margin_of_error = t_critical * se_delta,
            delta_low = mean_delta - margin_of_error,
            delta_high = mean_delta + margin_of_error)


#print out formula_CI 
formula_ci</code></pre>
<pre><code>## # A tibble: 1 × 9
##   interval     mean_de…¹ SD_de…² count…³ se_de…⁴ t_cri…⁵ margi…⁶ delta…⁷ delta…⁸
##   &lt;chr&gt;            &lt;dbl&gt;   &lt;dbl&gt;   &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1 2011-present      1.07   0.265     144  0.0221    1.98  0.0437    1.02    1.11
## # … with abbreviated variable names ¹​mean_delta, ²​SD_delta, ³​count_delta,
## #   ⁴​se_delta, ⁵​t_critical, ⁶​margin_of_error, ⁷​delta_low, ⁸​delta_high</code></pre>
<pre class="r"><code>#using formula
formula_ci %&gt;% 
  select(delta_low,delta_high)</code></pre>
<pre><code>## # A tibble: 1 × 2
##   delta_low delta_high
##       &lt;dbl&gt;      &lt;dbl&gt;
## 1      1.02       1.11</code></pre>
<pre class="r"><code>#using bootstrap simulation
mean_delta &lt;- comparison %&gt;% 
  filter(interval==&quot;2011-present&quot;) %&gt;% 
  specify(response=delta) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;% 
  calculate(stat=&quot;mean&quot;)


percentile_ci &lt;- mean_delta %&gt;% 
  get_confidence_interval(level=0.95,type=&quot;percentile&quot;)
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.03     1.11</code></pre>
<blockquote>
<p><strong>Using some of the summary statistics we calculated, we determined the t-critical value and margin of error. From this we were able to find the confidence interval for the sample mean. The 95% confidence interval for average annual temperature change is [1.02, 1.11] using both the formula and bootstrap simulation. It means that we can be 95% confident that the true mean temperature delta lies in this interval.The data suggests that from 2011 to today, the annual temperature increase is above one degree, which may significantly affect the global environment. Contrary to what the Donald believes, the data does not lie and global warming is indeed real.</strong></p>
</blockquote>
</div>
